services:
  api:
    restart: "no"  # Ensures that Docker doesn't automatically restart after failure
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/build
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=host.docker.internal
      - REDIS_URL=redis:6379
      - REDIS_URL=redis://host.docker.internal:6379
    env_file:
      - .env
    command: air ./main.go -b 0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/general/site-detail"]  # Health check endpoint
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    networks:
      - shared_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    env_file:
      - .env
    ports:
      - "5050:80"
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
